version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env  

  server:
    build:
      context: ./server
    ports:
      - "5001:5001" 
    depends_on:
      - db
    env_file:
      - ./server/.env.docker  

  db:
    build:
      context: ./db  
    ports:
      - "5432:5432"
    image: postgres
    env_file:
      - ./server/.env.docker