version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env  
    depends_on:
      - db
    environment:
      - DOCKER_ENV=true
      - PORT=${PORT} 

  db:
    ports:
      - "5432:5432"
    image: postgres
    env_file:
      - ./db/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}   
