version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5001"
    depends_on:
      - db

  db:
    build:
      context: ./db
      args:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    image: postgres
    env_file: ./db/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
