name: OpenAPI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Swagger UI Action
        uses: Legion2/swagger-ui-action@v1.2.0
        with:
          spec-url: "http://localhost:8080/swagger-ui.html"

      - name: Validate Swagger and OpenAPI using Swagger CLI
        uses: mbowman100/swagger-validator-action@2.0
        with:
          spec-file: ".openApi.yml"
